### ISSUE TITLE
Can drivers signed using PastDSE be used on Windows 11?

### ISSUE THREAD

**Issue by DavidBerdik** [utoni/PastDSE#1]
Can drivers signed using PastDSE be used on Windows 11?

**Comment by utoni** [comment]
Windows 11 is untested.

But for the signing process itself you need signtool which is part of Visual Studio. In theory it should work.

**Comment by DavidBerdik** [comment]
Alright, thanks! The reason I ask is because I previously used to use the leaked HT Srl certificate for signing, but on newer versions of Windows 10 as well as on Windows 11, trying to use a driver signed with it fails.

I am not sure what the last version of 10 was to allow the HT Srl cert to work. I'm hoping to give your tool a try as a solution to this.

Also, do you have a precompiled version of the `sys` available for download somewhere and I just haven't seen it?

**Comment by utoni** [comment]
> I am not sure what the last version of 10 was to allow the HT Srl cert to work. I'm hoping to give your tool a try as a solution to this.

Supportet: Windows 10 x64 1803, 1809 and 1903 

> Also, do you have a precompiled version of the sys available for download somewhere and I just haven't seen it?

See ![bin\x64\Debug](https://github.com/lnslbrty/PastDSE/tree/master/bin/x64/Debug) or ![bin\x64\Release](https://github.com/lnslbrty/PastDSE/tree/master/bin/x64/Release)

**Comment by DavidBerdik** [comment]
> Supportet: Windows 10 x64 1803, 1809 and 1903

I saw this, but I thought it referred to the versions of Windows on which signing was supported. I didn't think it had anything to do with the versions on which running those signed files would work.

Are you using the same Ht Srl certificate for this tool?

>See bin\x64\Debug or bin\x64\Release

Thanks!

**Comment by utoni** [comment]
> I saw this, but I thought it referred to the versions of Windows on which signing was supported. I didn't think it had anything to do with the versions on which running those signed files would work.

I probably need to clarify that in the `README.md`. Thanks for pointing that out.

> Are you using the same Ht Srl certificate for this tool?

You can view the content of the ![cert](https://github.com/lnslbrty/PastDSE/blob/master/certs/cert_0.pfx) that is used for signing.

**Comment by DavidBerdik** [comment]
>I probably need to clarify that in the README.md . Thanks for pointing that out.

Aww well that's a bummer. You're welcome, though!

>You can view the content of the cert that is used for signing.

Awesome! Thank you.
